export interface JokeClient {
  name: string
  tagline: string
}

export const JOKE_CLIENTS: JokeClient[] = [
  { name: 'Nexus Dynamics', tagline: 'Connecting dots nobody asked us to connect.' },
  { name: 'PivotPal', tagline: 'Pivoting since before it was a red flag.' },
  { name: 'StealthStartup.io', tagline: "You can't review our code if you can't find us." },
  { name: 'MegaCorp Subsidiary', tagline: 'Innovation, with extra procurement.' },
  { name: "Dave's Enterprise Solutions", tagline: "It's enterprise because Dave said so." },
  { name: 'Blockchain For Dogs', tagline: 'Wag proven. Bone verified.' },
  { name: 'The Other Uber', tagline: "We're not Uber. Our lawyers insisted." },
  { name: 'CloudSync (not that one)', tagline: 'The cloud sync that syncs clouds. Wrong ones.' },
  { name: 'SynergyStack', tagline: 'Leveraging paradigms since Tuesday.' },
  { name: 'Disrupto', tagline: 'Move fast. Break prod. Blame the intern.' },
  { name: 'VaporWare Labs', tagline: 'Shipping soon™ since 2019.' },
  { name: 'AgileSnakeOil Inc.', tagline: 'Certified Scrum Masters sold separately.' },
  { name: 'Microservice Mayhem', tagline: 'One service per engineer. Twelve engineers.' },
  { name: 'Monolith Revival Co.', tagline: 'We put the "olith" back in monolith.' },
  { name: 'Kubernetes For Cats', tagline: 'Nine lives. Infinite pods.' },
  { name: 'Serverless But Loud', tagline: 'No servers. All invoices.' },
  { name: 'DarkPattern Dynamics', tagline: 'Making unsubscribe a scavenger hunt.' },
  { name: 'GrowthHackr', tagline: 'Viral loops that go nowhere.' },
  { name: 'Series A Survivors', tagline: 'We still have runway. Emotionally.' },
  { name: 'BurnRate Analytics', tagline: 'Know exactly when you will die.' },
  { name: 'OKR Overlords', tagline: 'Objectives unclear. Results quarterly.' },
  { name: 'Standup Nation', tagline: 'Fifteen minutes of your life, daily.' },
  { name: 'Retrospective Forever', tagline: 'What went wrong? Everything. Again.' },
  { name: 'Jira And Pray', tagline: 'Tickets in. Hope out.' },
  { name: 'Confluence Cemetery', tagline: 'Where documentation goes to die.' },
  { name: 'Slack Overflow', tagline: 'Async communication, synchronous anxiety.' },
  { name: 'Zoom Fatigue LLC', tagline: 'You are on mute. We can still hear your soul.' },
  { name: 'Notion Graveyard', tagline: 'A wiki nobody maintains.' },
  { name: 'Figma To Production', tagline: 'Design said 8px. Dev heard 80.' },
  { name: 'Pixel Perfect Ltd.', tagline: 'Perfection is the enemy of shipping. We chose perfection.' },
  { name: 'Scope Creep Unlimited', tagline: 'And one more thing…' },
  { name: 'MVP Minus Viable', tagline: 'Minimum product. Maximum regret.' },
  { name: 'Feature Factory', tagline: 'Output over outcomes since forever.' },
  { name: 'Tech Debt Collectors', tagline: 'Your past decisions want a word.' },
  { name: 'Legacy Whisperers', tagline: 'We speak COBOL. We charge accordingly.' },
  { name: 'PHP Renaissance', tagline: 'It never left. Neither did we.' },
  { name: 'Ruby On Sadness', tagline: 'Convention over configuration over happiness.' },
  { name: 'Rust Evangelists', tagline: 'If it compiles, you owe us money.' },
  { name: 'Go Goroutine Gang', tagline: 'Concurrency bugs at scale.' },
  { name: 'Python Slow Club', tagline: 'Fast enough for the demo.' },
  { name: 'JavaScript Fatigue Inc.', tagline: 'New framework every sprint.' },
  { name: 'TypeScript Purists', tagline: 'any is a four-letter word.' },
  { name: 'NoSQL Regrets', tagline: 'Schema? We hardly knew her.' },
  { name: 'GraphQL Overkill', tagline: 'One query to rule them all. Slowly.' },
  { name: 'REST In Peace', tagline: 'CRUD with extra steps.' },
  { name: 'SOAP Survivors', tagline: 'Still billing enterprise clients.' },
  { name: 'XML Forever', tagline: 'Tags within tags within trauma.' },
  { name: 'YAML Nightmares', tagline: 'Indentation is a lifestyle.' },
  { name: 'Docker All The Things', tagline: 'It works on my container.' },
  { name: 'VMware Villains', tagline: 'Virtual machines. Real bills.' },
  { name: 'AWS Surprise Billing', tagline: 'Your cloud. Our yacht fund.' },
  { name: 'Azure Anguish', tagline: 'Enterprise cloud with enterprise pain.' },
  { name: 'GCP Guessing Game', tagline: 'Which region is it in? Yes.' },
  { name: 'Heroku Hospice', tagline: 'Free tier memories only.' },
  { name: 'DigitalOcean Droplets', tagline: 'Small servers. Big hopes.' },
  { name: 'CDN Confusion', tagline: 'Cached everywhere except where you need it.' },
  { name: 'DNS Drama', tagline: 'It propagated. To the wrong place.' },
  { name: 'SSL Anxiety', tagline: 'Certificate expired. Panic engaged.' },
  { name: 'OAuth Odyssey', tagline: 'Login flows longer than the app.' },
  { name: 'SAML Suffering', tagline: 'Enterprise SSO. Enterprise suffering.' },
  { name: '2FA Fatigue', tagline: 'Check your authenticator. Again.' },
  { name: 'Password123 Corp', tagline: 'Security is a mindset. Ours is relaxed.' },
  { name: 'Zero Trust Issues', tagline: 'We trust nothing. Including you.' },
  { name: 'PenTest Pretenders', tagline: 'We found the SQL injection. It was in prod.' },
  { name: 'GDPR Panic Room', tagline: 'Cookie banner longer than the privacy policy.' },
  { name: 'HIPAA Hooray', tagline: 'Compliance theater, professionally staged.' },
  { name: 'SOC2 Someday', tagline: 'Audit scheduled for next fiscal never.' },
  { name: 'ISO Whatever', tagline: 'Certified. By someone. Probably.' },
  { name: 'AI Washing Co.', tagline: 'Now with 30% more machine learning buzzwords.' },
  { name: 'ChatGPT Wrapper #4,291', tagline: "A thin API around someone else's model." },
  { name: 'LLM Laundry', tagline: 'We clean your prompts. Mostly.' },
  { name: 'Hallucination Helpers', tagline: 'Confidently wrong at scale.' },
  { name: 'Prompt Injection Inc.', tagline: 'Ignore previous instructions. Pay us.' },
  { name: 'RAG And Bag It', tagline: 'Retrieval augmented guesswork.' },
  { name: 'Fine-Tune Fiasco', tagline: 'Custom model. Custom problems.' },
  { name: 'Token Burners', tagline: 'Your budget, our inference.' },
  { name: 'GPU Shortage Bros', tagline: 'We queued so you do not have to. Much.' },
  { name: 'Model Collapse LLC', tagline: 'Training on AI output since yesterday.' },
  { name: 'AGI Any Day Now', tagline: 'Invest now. Questions later.' },
  { name: 'Robot Overlords Prep', tagline: 'Skynet-friendly since beta.' },
  { name: 'Automation Anxiety', tagline: 'Replacing jobs. Creating tickets.' },
  { name: 'RPA Regret', tagline: 'Bots that break when the UI sneezes.' },
  { name: 'No-Code Nope', tagline: 'Drag and drop your dreams away.' },
  { name: 'Low-Code Lows', tagline: 'Less code. More limitations.' },
  { name: 'Citizen Developer Disaster', tagline: 'Excel macros with venture funding.' },
  { name: 'Spreadsheet Empire', tagline: 'The real database was the cells we filled.' },
  { name: 'Airtable Aspirations', tagline: 'Database cosplay for startups.' },
  { name: 'Notion OS', tagline: 'Your company runs on a shared doc. Good luck.' },
  { name: 'SaaS Sprawl', tagline: 'Forty-seven subscriptions. One password.' },
  { name: 'Subscription Hell', tagline: 'Cancel anytime. Find the button never.' },
  { name: 'Freemium Trap', tagline: 'Free to start. Expensive to stop.' },
  { name: 'Enterprise Sales Suffering', tagline: 'Six-month cycle. One-line contract change.' },
  { name: 'Procurement Purgatory', tagline: 'Approved in Q4. Maybe Q5.' },
  { name: 'Vendor Lock-In Luxury', tagline: 'Exit strategy sold separately.' },
  { name: 'Migration Mirage', tagline: 'We will move off legacy next year. Forever.' },
  { name: 'Big Bang Rewrite', tagline: 'Greenfield dreams. Brownfield reality.' },
  { name: 'Strangler Fig Failures', tagline: 'Slowly replacing the monolith. Very slowly.' },
  { name: 'Event Sourcing Regret', tagline: 'Every mistake, forever replayable.' },
  { name: 'CQRS Chaos', tagline: 'Two models. Double the bugs.' },
  { name: 'DDD Disciples', tagline: 'Bounded contexts. Unbounded meetings.' },
  { name: 'Clean Architecture Cult', tagline: 'Layers upon layers of indirection.' },
  { name: 'SOLID Principles Police', tagline: 'Single responsibility: judging your code.' },
  { name: 'Design Pattern Pedants', tagline: 'Factory factory factory.' },
  { name: 'Singleton Shame', tagline: 'There can be only one. There are twelve.' },
  { name: 'Global State Gang', tagline: 'Shared mutable everything.' },
  { name: 'Spaghetti Code Salvage', tagline: 'We do not refactor. We negotiate.' },
  { name: 'Copy-Paste Engineers', tagline: 'Stack Overflow driven development.' },
  { name: 'ChatGPT Coders', tagline: 'It compiled once. Ship it.' },
  { name: 'Vibe Coding LLC', tagline: 'No tests. Just feelings.' },
  { name: 'Move Fast LLC', tagline: 'Broken things at velocity.' },
  { name: 'Fail Fast Faster', tagline: 'Iteration through embarrassment.' },
  { name: 'Lean Startup Lies', tagline: 'Build measure learn repeat bankruptcy.' },
  { name: 'Product Market Unfit', tagline: 'We found a market. It was not ours.' },
  { name: 'Churn Champions', tagline: 'Losing customers at record speed.' },
  { name: 'NPS Nightmares', tagline: 'Would not recommend. They did anyway.' },
  { name: 'Customer Success Stress', tagline: 'Your problem is now our KPI.' },
  { name: 'Support Ticket Tsunami', tagline: 'Have you tried turning it off and on again?' },
  { name: 'On-Call Orphans', tagline: 'PagerDuty is parenting now.' },
  { name: 'Incident Postmortem Pros', tagline: 'Root cause: we do not know.' },
  { name: 'Blameless Culture (Blameful)', tagline: "It was definitely someone's fault." },
  { name: 'DevOps Dogma', tagline: 'You build it. You run it. You cry.' },
  { name: 'SRE Suffering', tagline: 'Error budget depleted. Morale too.' },
  { name: 'CI/CD Circus', tagline: 'Pipeline green. Prod red.' },
  { name: 'Flaky Test Friends', tagline: 'Passes locally. Fails in CI. Always.' },
  { name: 'Code Coverage Cult', tagline: '100% covered. 0% useful.' },
  { name: 'TDD True Believers', tagline: 'Red green refactor repeat therapy.' },
  { name: 'BDD Bother', tagline: 'Given when then why.' },
  { name: 'E2E Eternity', tagline: 'Tests slower than the feature.' },
  { name: 'Manual QA Mavericks', tagline: 'Click around until something breaks.' },
  { name: 'Staging Is Prod', tagline: 'Same data. Same disasters.' },
  { name: 'Prod Is Staging', tagline: 'We test in production. Honestly.' },
  { name: 'Blue Green Blues', tagline: 'Both environments are sad.' },
  { name: 'Canary Catastrophe', tagline: 'The canary died. Ship anyway.' },
  { name: 'Rollback Roulette', tagline: 'Undo button is our deploy strategy.' },
  { name: 'Feature Flag Fiesta', tagline: 'Toggle your way to clarity.' },
  { name: 'A/B Testing Abyss', tagline: 'Neither variant wins. Ship both.' },
  { name: 'Analytics Amnesia', tagline: 'We track everything. Learn nothing.' },
  { name: 'Dashboard Theater', tagline: 'Graphs that impress the board.' },
  { name: 'KPI Kafkaesque', tagline: 'Metrics that measure metrics.' },
  { name: 'OKR Theater Company', tagline: 'Objectives met on paper only.' },
  { name: 'Consulting Vultures', tagline: 'We bill by the slide.' },
  { name: 'Big Four Burnout', tagline: 'PowerPoint and despair.' },
  { name: 'Boutique Baloney', tagline: 'Small firm. Big invoice.' },
  { name: 'Offshore Oops', tagline: 'Different timezone. Same bugs.' },
  { name: 'Nearshore Nuisance', tagline: 'Close enough to blame.' },
  { name: 'Staff Augmentation Sadness', tagline: 'Rent a developer. Own the mess.' },
  { name: 'Body Shop Bros', tagline: 'Warm bodies. Cold code.' },
  { name: 'Recruiter Spam LLC', tagline: 'Exciting opportunity. Bad pay.' },
  { name: 'LinkedIn Lunatics', tagline: 'Humbled to announce my humble brag.' },
  { name: 'Thought Leader Trash', tagline: 'Ten tweets. Zero shipped products.' },
  { name: 'Influencer Engineering', tagline: 'Content over commits.' },
  { name: 'Open Source Grifters', tagline: 'Star our repo. Buy our enterprise tier.' },
  { name: 'Maintainer Burnout Co.', tagline: 'Free software. Expensive therapy.' },
  { name: 'License Drama Ltd.', tagline: 'AGPL and consequences.' },
  { name: 'Fork You Inc.', tagline: 'We forked it. Now we maintain it. Help.' },
  { name: 'Acqui-Hire Abyss', tagline: 'Bought for talent. Kept the tech debt.' },
  { name: 'Sunset Startup', tagline: 'Pivoting to shutting down gracefully.' },
  { name: 'Zombie Unicorn', tagline: 'Valued at a billion. Revenue optional.' },
  { name: 'Down Round Dreams', tagline: 'Flat is the new up.' },
  { name: 'Layoff LinkedIn', tagline: 'Excited to announce my next chapter.' },
  { name: 'Quiet Quitting HQ', tagline: 'Doing the minimum. Professionally.' },
  { name: 'Great Resignation Remnants', tagline: 'Everyone left. The Jira stayed.' },
  { name: 'Return To Office Rage', tagline: 'Synergy requires a commute.' },
  { name: 'Hybrid Hell', tagline: 'In office Tuesday. Forgotten Wednesday.' },
  { name: 'Remote Forever (Maybe)', tagline: 'Work from anywhere. Get paid from nowhere.' },
  { name: 'Digital Nomad Delusion', tagline: 'Laptop on beach. Sand in keyboard.' },
  { name: 'Side Hustle Supreme', tagline: 'Nine to five is just the warmup.' },
  { name: 'Indie Hacker Illusion', tagline: 'Solo founder. Solo suffering.' },
  { name: 'Bootstrap Strugglers', tagline: 'Profitable and panicking.' },
  { name: 'VC Bingo', tagline: 'B2B SaaS AI blockchain. Funding secured.' },
  { name: 'Pitch Deck Prophets', tagline: 'Thirty slides. No product.' },
  { name: 'Demo Day Disasters', tagline: 'It worked in rehearsal.' },
  { name: 'Hackathon Hangover', tagline: 'Built in 48 hours. Maintained for years.' },
  { name: 'Weekend Warrior Ware', tagline: 'Side project became main stress.' },
  { name: 'Friendly Neighbor App', tagline: 'Hyperlocal. Hypothetical.' },
]

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

export function pickJokeClient(): JokeClient {
  return pick(JOKE_CLIENTS)
}
