import type { ModelDef } from './types'

export const MODELS: Record<string, ModelDef> = {
  'local-7b': {
    id: 'local-7b',
    name: 'Llama Lite 7B',
    kind: 'local',
    tagline: 'Free. Depressing. Like instant coffee.',
    parameters: 7,
    contextSize: 8,
    ramCost: 4,
    successChance: 0.42,
    contextFillRate: 0.35,
    tokenCostPerTick: 0,
    purchaseCost: 0,
    localTickCap: 0.45,
    deployCost: 0,
  },
  'local-13b': {
    id: 'local-13b',
    name: 'Mistral Meh 13B',
    kind: 'local',
    tagline: 'Shelf ware with ambition issues.',
    parameters: 13,
    contextSize: 16,
    ramCost: 8,
    successChance: 0.55,
    contextFillRate: 0.28,
    tokenCostPerTick: 0,
    purchaseCost: 0,
    localTickCap: 0.55,
    deployCost: 0,
  },
  'local-34b': {
    id: 'local-34b',
    name: 'CodeLlama 34B',
    kind: 'local',
    tagline: 'Big params. Small apartment dreams.',
    parameters: 34,
    contextSize: 32,
    ramCost: 16,
    successChance: 0.68,
    contextFillRate: 0.22,
    tokenCostPerTick: 0,
    purchaseCost: 0,
    localTickCap: 0.65,
    deployCost: 0,
  },
  'fab-lite': {
    id: 'fab-lite',
    name: 'Fabulous5 Lite',
    kind: 'cloud',
    tagline: 'Cloud candy. Token meter spins.',
    parameters: 20,
    contextSize: 64,
    ramCost: 0,
    successChance: 0.72,
    contextFillRate: 0.18,
    tokenCostPerTick: 1.2,
    purchaseCost: 0,
    localTickCap: 1,
    deployCost: 25,
  },
  'fab-pro': {
    id: 'fab-pro',
    name: 'Fabulous5 Pro',
    kind: 'cloud',
    tagline: 'Actually ships code. Financially ruins you.',
    parameters: 70,
    contextSize: 128,
    ramCost: 0,
    successChance: 0.86,
    contextFillRate: 0.12,
    tokenCostPerTick: 3.5,
    purchaseCost: 0,
    localTickCap: 1,
    deployCost: 60,
  },
  'fab-ultra': {
    id: 'fab-ultra',
    name: 'Fabulous5 Ultra',
    kind: 'cloud',
    tagline: 'CEO-tier inference. Intern-tier budget required.',
    parameters: 200,
    contextSize: 256,
    ramCost: 0,
    successChance: 0.94,
    contextFillRate: 0.08,
    tokenCostPerTick: 8,
    purchaseCost: 0,
    localTickCap: 1,
    deployCost: 120,
  },
}

export const LOCAL_MODEL_LIST = Object.values(MODELS).filter((m) => m.kind === 'local')
export const CLOUD_MODEL_LIST = Object.values(MODELS).filter((m) => m.kind === 'cloud')

export function getModel(id: string): ModelDef {
  return MODELS[id]
}
