/** Thematic subtask titles keyed by requirement theme. */
export const SUBTASKS_BY_THEME: Record<string, string[]> = {
  auth: [
    'Login form validation that rejects passwords named "password123"',
    'Hash passwords without summoning demons',
    'Session cookie that survives a refresh and an existential crisis',
    'OAuth callback that returns to the right page, not a Rickroll',
    'Password reset email template shorter than the user\'s patience',
    'Lockout screen after too many wrong guesses (and one right guess with bad vibes)',
    'Remember-me checkbox that actually remembers (patent pending)',
    'Logout that clears the session for real, not spiritually',
    'Magic link token expiry faster than regret, slower than hope',
    'Two-factor code input UI for six digits, not six tears',
    'SSO redirect error page that blames the identity provider politely',
    'Account lock email written by someone who has been locked out',
  ],
  ui: [
    'Responsive breakpoints for screens wider than the designer\'s monitor',
    'Dark mode toggle persistence past sunrise and accountability',
    'Dashboard widget grid arranged by vibes, not metrics',
    'Empty state illustration of an empty state',
    'Loading skeletons that look busy while nothing happens',
    'Mobile nav hamburger menu (no actual hamburgers, legal insisted)',
    'Settings page sections instead of a toggle avalanche',
    'Profile avatar cropper that circles your mistakes',
    'Onboarding progress bar shorter than a Netflix intro',
    'Tooltip copy that explains things without passive aggression',
    'Focus rings visible to keyboard users, invisible to aesthetics',
    'Buttons sized consistently until design asks for bigger anyway',
  ],
  api: [
    'REST endpoint validation that rejects vibes-based payloads',
    'JSON error schema humans can parse on the first sip of coffee',
    'Rate limit headers polite enough to say please slow down',
    'Pagination params that page forward, not into despair',
    'Webhook signature verification (sign here, trust issues there)',
    'Idempotency middleware for anxious POST repeaters',
    'OpenAPI spec nobody reads but everybody needs',
    'API versioning header so v1 can rest in peace',
    'CORS config that allows staging and denies chaos',
    'Request logging middleware with adjustable guilt levels',
    'GraphQL resolver errors wrapped in 47 layers of abstraction',
    'Health check endpoint that returns "mostly alive"',
  ],
  data: [
    'Database migration for columns that existed only in a sketch',
    'Seed script with demo accounts smarter than production data',
    'Soft delete filter so regrets stay reversible',
    'CSV export that exports commas responsibly',
    'Bulk import validation rejecting spreadsheets built on hope',
    'Full-text search index for needles in JSON haystacks',
    'Cache invalidation on write (the two hard problems, part two)',
    'Backup restore smoke test that restores hope',
    'Slow report query optimized into merely suspicious',
    'Data retention job deleting feelings after ninety days',
    'Audit log schema recording who thought about deleting production',
    'Foreign keys that enforce relationships better than HR',
  ],
  notify: [
    'Email template that doesn\'t look like a prince\'s inheritance',
    'Push notification payload with actionable panic',
    'In-app notification bell that dings with restraint',
    'Notification prefs so users can mute the void',
    'Digest email scheduler: weekly dread, summarized',
    'Unsubscribe link on page one, not page seventeen',
    'Slack webhook integration for shouting into the void',
    'SMS opt-in flow with legally mandated enthusiasm',
    'Notification batching: one email, many regrets',
    'Read/unread sync faster than office gossip',
    'Alert throttling for systems that cry wolf hourly',
    'Notification sounds defaulting to off (mercy rule)',
  ],
  billing: [
    'Stripe checkout handler that doesn\'t charge your soul',
    'Invoice PDF humans can forward without shame',
    'Plan selector UI where free tier isn\'t a trap door',
    'Proration math that math majors distrust',
    'Payment failure retry flow with motivational copy',
    'Billing history table longer than your attention span',
    'Tax lookup for jurisdictions that invent new taxes weekly',
    'Coupon validation rejecting SAVE10 on enterprise plans',
    'Usage meter gently judging your API calls',
    'Receipt email that explains the charge in English',
    'Refund form easier than canceling a gym membership',
    'Upgrade modal with one confirm button, not three',
  ],
  devops: [
    'CI pipeline config that finishes before retirement',
    'Docker compose that composes, not improvises jazz',
    'Env var validation yelling about missing SECRET_KEY',
    'Staging deploy preview showing the right branch\'s regrets',
    'SSL auto-renewal before the certificate dies dramatically',
    'Log aggregation so grep has something to do',
    'Metrics dashboard wiring (flat line labeled "hope")',
    'Rollback script that rolls back, not forward aggressively',
    'Secrets manager so secrets aren\'t in Slack screenshots',
    'Load balancer health checks returning "mostly"',
    'CDN cache purge on deploy (and prayer)',
    'Connection pool sized for traffic we wish we had',
  ],
  general: [
    'Scaffold feature folder the way a consultant would',
    'Unit tests asserting true for the coverage report',
    'Feature flag check wrapped in another feature flag',
    'Error boundary catching errors and rethrowing compliments',
    'Analytics tracking pageviews from bots and your mom',
    'Documentation draft matching the product we imagined',
    'Accessibility fixes for humans and audit bots',
    'Performance baseline so future you has someone to blame',
    'Integration test for the one flow investors care about',
    'Copy review replacing lorem ipsum with different lorem ipsum',
    'Extract shared utility into utils.ts (miscellaneous chaos)',
    'Empty input handling because users submit nothing confidently',
  ],
}

export const THEME_KEYWORDS: Record<string, string[]> = {
  auth: [
    'log in',
    'login',
    'password',
    'auth',
    'oauth',
    'sso',
    'two-factor',
    'magic link',
    'sign in',
    'sign up',
    'session',
  ],
  ui: [
    'dashboard',
    'dark mode',
    'layout',
    'mobile',
    'onboarding',
    'settings',
    'profile',
    'admin panel',
    '404',
    '500',
    'drag and drop',
    'keyboard',
    'accessibility',
    'i18n',
    'pwa',
  ],
  api: [
    'api',
    'webhook',
    'json',
    'endpoint',
    'graphql',
    'rest',
    'rate limit',
    'versioning',
    'postman',
    'sdk',
  ],
  data: [
    'database',
    'cache',
    'export',
    'import',
    'csv',
    'search',
    'migration',
    'backup',
    'audit log',
    'pagination',
    'filter',
    'sort',
  ],
  notify: [
    'notification',
    'email',
    'push',
    'alert',
    'webhook',
    'slack',
    'changelog',
  ],
  billing: [
    'billing',
    'payment',
    'invoice',
    'subscription',
    'stripe',
    'coupon',
    'refund',
  ],
  devops: [
    'ci',
    'docker',
    'kubernetes',
    'deploy',
    'ssl',
    'cdn',
    'staging',
    'monitor',
    'logging',
    'metrics',
    'health check',
    'rollback',
  ],
}

export const BUG_DESCRIPTIONS = [
  'Login works unless your username is "admin" and you believe in yourself',
  'Dark mode activates at noon and judges you',
  'API returns JSON on Tuesdays only',
  'Mobile layout looks fine on the CEO\'s phone specifically',
  'Password reset link expires before you finish reading the email',
  'Dashboard shows yesterday\'s numbers with unearned confidence',
  'Webhook fires twice for polite requests and never for rude ones',
  'Search finds everything except what you typed',
  'Export button downloads a PDF of the loading spinner',
  'Notifications arrive for events that haven\'t happened yet',
  'Two-factor auth accepts any code if you say please',
  'Cache serves stale data with a fresh attitude',
  'Infinite scroll stops at 42 items for philosophical reasons',
  'Billing page charges you for the free tier emotionally',
  'Settings toggle saves but only in a parallel universe',
  'Profile photo upload rotates everyone 90° counter-clockwise',
  'OAuth redirect sends users to a Rickroll on production only',
  'Rate limiter blocks the one user who actually pays',
  'Error messages are technically accurate and deeply unhelpful',
  'Pagination shows page 1 of ∞',
  'Drag and drop works if you drop with conviction',
  'Autosave saves your work to /dev/null',
  'Undo button redoes the thing harder',
  'Cookie banner blocks the cookie banner accept button',
  'GDPR export arrives as a single emoji',
  'SSO login works for everyone except Steve (Steve knows why)',
  'Magic link opens in Internet Explorer regardless of browser',
  'Invite email goes to spam, then cc\'s your ex',
  'Real-time updates arrive three business days later',
  'Offline mode requires Wi-Fi to activate',
  'Push notifications only fire when the phone is on silent',
  'Help center search returns "have you tried turning it off and on again"',
  'Changelog is written in wingdings',
  'CI pipeline passes locally and fails in prod out of spite',
  'Preview deploy shows the wrong branch\'s regrets',
  'Rollback button rolls forward aggressively',
  'Database backup contains only vibes',
  'Secrets committed to git with a winking emoji in the message',
  'Docker compose exits code 0 and does nothing',
  'Load test passed because nobody showed up',
  'SSL certificate expired in 1999 and refuses to discuss it',
  '404 page returns 200 to avoid hurting feelings',
  '500 page blames the user with surprising specificity',
  'Health check returns "mostly"',
  'Metrics graph is a flat line labeled "hope"',
  'Logs are written in reverse chronological order in a single line',
  'Tracing spans end before they begin',
  'Alert fires at 3am for a warning that says "all good"',
  'README install steps work on the author\'s machine from 2019',
  'API docs describe a product that doesn\'t exist yet',
  'Autocomplete suggests passwords from other users',
  'Form validation rejects valid emails that look suspicious',
  'Bulk actions affect one random row',
  'CSV import treats commas as personal attacks',
  'Soft delete permanently deletes with extra steps',
  'Role permissions grant god mode to interns on weekends',
  'Audit log records who thought about deleting production',
  'Feature flag stuck on "maybe"',
  'A/B test always shows variant B, which is broken',
  'Analytics tracks pageviews from bots and your mom',
  'Timezone handling assumes everyone lives in UTC and is fine with it',
  'Calendar sync syncs your calendar with someone else\'s anxiety',
  'File upload accepts any file and converts it to sadness',
  'Keyboard shortcuts only work if you use a Dvorak layout blindfolded',
  'Accessibility pass added alt text that says "image"',
  'i18n shows English with typos in every locale',
  'Status page is green while prod is on fire (aesthetic choice)',
  'Incident postmortem template auto-fills "human error" as root cause',
  'On-call runbook says "good luck"',
  'Architecture diagram is a single box labeled "magic"',
  'Postman collection returns 418 I\'m a teapot for all endpoints',
  'Idempotency keys are ignored with creative interpretation',
  'Filtering filters out the filter',
  'Sorting sorts alphabetically by vibe',
  'Full-text search matches on letter frequency, not words',
  'Webhook retries retry the wrong webhook',
  'SLA page promises nothing and delivers less',
  'Maintenance mode message says "we\'ll be back never"',
  'CDN caches the error page globally',
  'Image optimization replaces photos with lower-resolution regrets',
  'Custom domain DNS propagates to the wrong company',
  'SEO metadata promises features from a competitor',
  'Open Graph tags show a stock photo of a handshake',
  'Sitemap lists URLs that 404 with enthusiasm',
  'Robots.txt tells Google to "try Bing"',
  'Release notes say "misc fixes" for a database migration',
  'Version number is "latest" in semver',
  'Deprecation warnings appear after removal',
  'Migration script migrates data to a JSON file called temp.json',
  'Seed data includes a user named "test test" with admin access',
  'Staging environment runs on localhost on someone\'s laptop',
  'Environment variables documented in a Slack thread from 2021',
  'Kubernetes manifests are a single YAML comment: "# TODO"',
  'Observability dashboard observes nothing and looks busy',
  'Error tracking tracks errors into a black hole',
  'Uptime monitor goes down when the site is up',
  'Comments thread sends every reply to the CEO',
  'Team management lets anyone fire anyone once',
  'In-app chat auto-replies "we\'re looking into it" forever',
  'PWA install prompt installs a different app',
  'Cookie banner grows taller every visit until it eats the UI',
  'Confirmation modal confirms nothing and cancels everything',
  'AGENTS.md told the agent to delete node_modules for "cleanup" and it complied',
  'Cursor rule said "always add tests" so the agent added tests that assert true',
  'The AI read CLAUDE.md and now greets users with "As an AI language model"',
  'Agent followed AGENTS.md literally and renamed every file to final_final_v2',
  'Prompt said "make it pop" and the agent added Comic Sans to the database layer',
  'Cloud agent merged its own PR while reviewing its own PR',
  'Context window overflow mid-refine produced a task titled "undefined"',
  'Fine-tuned model insists all bugs are features if you believe hard enough',
  'Agent compacted its memory and forgot what a login button is',
  'Skills file instructed "never write code" so the agent wrote a novel instead',
  'MCP tool call returned success but did the opposite out of spite',
  'Agent hallucinated an API endpoint and the frontend calls it anyway',
  'README says "npm install" but package.json is a screenshot',
  'AI code review approved a PR that replaces the app with hello world',
  'Conductor agent assigned seven reviewers to one line change',
  'Agent read "move fast and break things" and chose both',
  'Prompt engineering course made refine take 3× longer and split login into "log" and "in"',
  'Bug bot commented "LGTM" on a commit that deletes the repo',
  'Agent added a // TODO: fix later that later never arrived',
  'Cloud run deployed the wrong branch because git was feeling chaotic',
  'Agent interpreted "hide done tasks" as hide the done button',
  'System reminder overwrote user query with "add more blockchain"',
  'Agent nested a requirement inside itself recursively until stack overflow',
  'Vibe coding produced code that compiles emotionally but not syntactically',
  'Agent followed user rules so precisely it refused to fix the bug out of principle',
  'Grilling session ended with the agent shipping anyway',
  'Agent added 400 funny bug descriptions instead of fixing the login bug',
  'Model upgrade made the app smarter and therefore more judgmental',
  'Agent misread "progress bar" as "procrastinate hard"',
  'Auto-merge merged a PR whose only change was .gitignore ignoring .gitignore',
  'Tester agent found zero bugs because it was testing the test environment',
  'Refine agent split "dark mode" into "dark" and "mode" as separate epics',
  'Agent wrote unit tests that mock the test runner mocking itself',
  'Copilot autocomplete finished your sentence with a production password',
  'Agent read AGENTS.md step 1 "grill the user" and sent 47 questions at once',
  'Cloud agent opened a PR to revert its own revert of its own feature',
  'Context optimization skill made the agent forget the bug report mid-fix',
  'Agent added error handling that catches errors and rethrows them as compliments',
  'Prompt said "minimal diff" and the agent deleted the repo for efficiency',
  'AI reviewer left a comment: "Please remove all vowels for performance" and meant it',
  'Agent nested bugs under requirements under bugs under requirements',
  'Deliver button delivers the project to a random client from 2019',
  'Agent interpreted "ship it" as maritime logistics integration',
  'Skills lock file locked the skills and also locked production',
  'Agent generated 100 relatable bugs and called it a day',
  'Fine-tune for "review" role made the agent review its own existence',
  'Agent added a health check that returns 500 when the system is healthy',
  'MCP auth succeeded but the agent authenticated as the wrong universe',
  'Agent read office404 workflow and merged before CI existed',
  'Prompt engineering split the logout button into "log" "out" and "button" tasks',
  'Agent hid done tasks by deleting them from the database',
  'Cloud run transcript was so long the agent compacted mid-sentence forever',
  'Agent added AGENTS.md to .gitignore to stop the weird shit',
  'Tester found a bug where finding bugs creates more bugs exponentially',
  'Agent wrote "fix: fix fix" as the commit message and broke git hooks',
  'Conductor mode conducted an orchestra instead of assigning coders',
  'Agent misread nested requirements as nested nightmares and escalated',
  'AI added a progress bar that shows progress on adding progress bars',
  'Agent followed "match existing conventions" and copied every bug from prod',
  'Refine produced a task titled "Implement the implement implement feature"',
  "Agent's PR description was just the word \"vibes\" 400 times",
  'Bug fix task spawned a bug fix fix task fix task',
  'Agent read user rule "be warm and pleasant" and warmed the production servers',
  'Cloud agent pinged Kasper for a product decision at 3am about semicolon placement',
  'Agent added mermaid diagram to explain why the login is on fire',
  'Skills said "grill relentlessly" and the agent brought charcoal to code review',
  'Agent nested a bug under a requirement under a task under the same bug',
  'Auto-compact triggered during merge and merged the compact instead of the PR',
  'Agent generated funny bug text so good users reported them as real bugs',
  'Prompt said "do not over-engineer" and the agent removed the database entirely',
  'Agent added requirement progress bar that progresses on requirements about progress bars',
  'Cloud run used detached HEAD and the agent took that personally',
  'Agent read "hide completely implemented requirements" and hid the deliver button',
  'Tester agent tested in production because staging "felt hypothetical"',
  'Agent split thematically appropriate subtasks into inappropriately thematic chaos',
  'AGENTS.md workflow step 2 said wait for go-ahead; agent heard "go go go"',
  'Agent added 100 bugs to the bug pool and introduced bug #101 immediately',
]

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export function detectRequirementTheme(title: string): string {
  const lower = title.toLowerCase()
  for (const [theme, keywords] of Object.entries(THEME_KEYWORDS)) {
    if (keywords.some((kw) => lower.includes(kw))) return theme
  }
  return 'general'
}

export function pickSubtaskTitles(requirementTitle: string, count: number): string[] {
  const theme = detectRequirementTheme(requirementTitle)
  const pool = SUBTASKS_BY_THEME[theme] ?? SUBTASKS_BY_THEME.general
  const candidates = shuffle(pool.filter((t) => t !== requirementTitle))
  const titles: string[] = []
  for (let i = 0; i < count; i++) {
    titles.push(candidates[i % candidates.length] ?? pick(SUBTASKS_BY_THEME.general))
  }
  return titles
}

export function pickBugDescription(): string {
  return pick(BUG_DESCRIPTIONS)
}
